name: CI
on:
  push:
    branches: [ main ]

jobs:
  hello:
    runs-on: self-hosted
    steps:
      - shell: pwsh
        env:
          SUPER_SECRET: ${{ secrets.SuperSecret }}
        run: |
          example-command "$env:SUPER_SECRET"
