name: CI
on:
  push:
    branches: [ main ]

jobs:
  hello:
    runs-on: self-hosted
    steps:
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.SuperSecret }}
          run: |
            example-command "$SUPER_SECRET"
